// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsggIe3Vq6LwnVoJdm0CG3W6mOGw1kIUM',
    appId: '1:866793016648:web:fa92c8ebf9dfe5caf3f77d',
    messagingSenderId: '866793016648',
    projectId: 'ai-life-navigator-27187',
    authDomain: 'ai-life-navigator-27187.firebaseapp.com',
    storageBucket: 'ai-life-navigator-27187.firebasestorage.app',
    measurementId: 'G-JVZRFQ4W2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1o7k3I-YpM7bLT_uPlMOckMBR-9CpZZc',
    appId: '1:866793016648:android:965bf7fa20d7bf5ff3f77d',
    messagingSenderId: '866793016648',
    projectId: 'ai-life-navigator-27187',
    storageBucket: 'ai-life-navigator-27187.firebasestorage.app',
  );
}
